apiVersion: apps/v1
kind: Deployment

metadata:
  name: nasa-app

spec:
  replicas: 2

  selector:
    matchLabels:
      app: nasa-app

  template:
    metadata:
      labels:
        app: nasa-app

    spec:
      containers:
        - name: nasa-app2
          image: nasa-app:2.0
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 5001